# -*- coding: utf-8 -*-
"""exp_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mXsQ-NxNrlE-2gX0btw6v7oT9gPU501N
"""

!pip install -q google-genai python-dotenv

import os
from google import genai

def ask_llm(prompt):
    try:
        response = client.models.generate_content(
            model="gemini-3.6-flash",
            contents=prompt
        )

        return response.text

    except Exception as e:
        return f"Error: {e}"

# Iteration 0 - Baseline
prompt0 = (
    "Explain photosynthesis to a 10-year-old."
)

# Iteration 1 - Analogy + Short Explanation
prompt1 = (
    "You are a friendly science teacher. "
    "Explain photosynthesis to a 10-year-old using a simple analogy. "
    "Keep the explanation to 3 short sentences and avoid technical jargon."
)

# Iteration 2 - Mnemonic + Diagram
prompt2 = (
    "You are a friendly science teacher. "
    "Explain photosynthesis to a 10-year-old using a simple analogy. "
    "Keep the explanation short and avoid technical jargon. "
    "Include a simple memory trick and describe a basic diagram."
)


# ------------------------------------------------------------
# STEP 4: Store Prompts
# ------------------------------------------------------------

prompts = [
    prompt0,
    prompt1,
    prompt2
]

responses = []

for i, prompt in enumerate(prompts):

    print("\n" + "=" * 60)
    print(f"ITERATION {i}")
    print("=" * 60)

    print("\nPrompt:")
    print(prompt)

    response = ask_llm(prompt)

    responses.append(response)

    print("\nResponse:")
    print(response)

    print("\nAnalysis:")

    if i == 0:
        print(
            "The baseline prompt gives a general explanation, "
            "but it may contain technical terms or unnecessary details."
        )

    elif i == 1:
        print(
            "The prompt was improved by adding a friendly teacher role, "
            "a simple analogy, a short length requirement, and simple language."
        )

    else:
        print(
            "The prompt was further improved by adding a memory trick "
            "and a diagram description, making the concept easier to remember "
            "and visualize."
        )

print("\n" + "=" * 60)
print("FINAL SUMMARY")
print("=" * 60)

print("\nIteration 0:")
print("Basic explanation of photosynthesis.")

print("\nIteration 1:")
print("Improved clarity using analogy, simple language, and brevity.")

print("\nIteration 2:")
print("Added a memory trick and diagram description.")

print("\nOverall:")
print(
    "Each refinement improved the prompt while keeping the same task. "
    "The final prompt makes the explanation easier for a 10-year-old "
    "to understand, remember, and visualize."
)

with open(
    "experiment_3_results.txt",
    "w",
    encoding="utf-8"
) as file:

    for i in range(3):

        file.write("\n" + "=" * 60 + "\n")
        file.write(f"ITERATION {i}\n")
        file.write("=" * 60 + "\n\n")

        file.write("PROMPT:\n")
        file.write(prompts[i])
        file.write("\n\n")

        file.write("RESPONSE:\n")
        file.write(responses[i])
        file.write("\n\n")

    file.write("FINAL SUMMARY:\n")
    file.write(
        "Iteration 0 provided a basic explanation.\n"
        "Iteration 1 improved clarity through analogy and brevity.\n"
        "Iteration 2 improved memorability and visualization.\n"
    )

print("\n✅ Results saved to experiment_3_results.txt")

